version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDISTOGO_URL=redis://redis:6379
    depends_on:
      - redis
